version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: alx_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: alx_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data   # persistent Redis data

volumes:
  postgres_data:
  redis_data:           # named volume for Redis
